theme: jekyll-theme-cayman
show_downloads: true
title: Raspberry Pi Website Uptime Monitor
description: The device monitors a list of your websites and lets you know if any of them are down using the Raspberry Pi and some LEDs
